from enum import Enum


class HousingType(str, Enum):
    ONE_ROOM = "ONE_ROOM"
    TWO_ROOM = "TWO_ROOM"
    ROOMMATE = "ROOMMATE"
    APARTMENT = "APARTMENT"
    COMMERCIAL = "COMMERCIAL"


class HousingAmenity(str, Enum):
    FRIDGE = "FRIDGE"
    WASHER = "WASHER"
    AC = "AC"
    PARKING = "PARKING"
    TV = "TV"
    WARDROBE = "WARDROBE"
    BED = "BED"
    DESK = "DESK"
    SHOE_CABINET = "SHOE_CABINET"
    INDUCTION = "INDUCTION"
    MICROWAVE = "MICROWAVE"
    ELEVATOR = "ELEVATOR"
    DIGITAL_LOCK = "DIGITAL_LOCK"
    CCTV = "CCTV"
    BALCONY = "BALCONY"
    VERANDA_EXPANSION = "VERANDA_EXPANSION"
    GAS_RANGE = "GAS_RANGE"
    INTERNET = "INTERNET"
    PET_FRIENDLY = "PET_FRIENDLY"
    HEATING_FLOOR = "HEATING_FLOOR"


class HousingStatus(str, Enum):
    ACTIVE = "ACTIVE"
    RESERVED = "RESERVED"
    RENTED = "RENTED"


class HousingDirection(str, Enum):
    NORTH = "NORTH"
    NORTHEAST = "NORTHEAST"
    EAST = "EAST"
    SOUTHEAST = "SOUTHEAST"
    SOUTH = "SOUTH"
    SOUTHWEST = "SOUTHWEST"
    WEST = "WEST"
    NORTHWEST = "NORTHWEST"
